# Generated by Django 4.0.2 on 2022-05-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization',
            name='AssayID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='MachineID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
