# Generated by Django 4.0.2 on 2022-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_alter_utilization_assayid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedrevenue',
            name='AssayID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missedrevenue',
            name='MachineID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlystats',
            name='AssayID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlystats',
            name='MachineID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='AssayID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='MachineID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='AssayID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stats',
            name='MachineID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
